general: &general
  name: "debug"
  model_name: "test_model"
  seed: 42
  device: "cuda"
  gpus: [0, 1]
  log_dir: "./log_dir"
  num_classes: 1
  task: "classification"
  encoder: "Imagenet:resnet50"
  decoder: "fc"
  data_source: "folder" # choose from ["folder", "list"]
  dataset_path: "/mnt/data2/users/hilight/yiwei/dataset/FakeSocial/"
  checkpoints_dir: "/mnt/data2/users/hilight/yiwei/train/checkpoints/"

train:
  <<: *general
  isTrain: True
  pretrained: True

  earlystop_epoch: 30
  epochs: 100
  loss_function: "bce" #["bce", "adam"]
  optimizer: "sgd"
  schedular:
  beta: 0.9
  weight_decay: 0.0
  momentum: 0.0
  learning_rate: 0.001
  init_type: "normal" #network initialization [normal|xavier|kaiming|orthogonal]
  init_gain: 0.02

  show_loss_freq: 400
  save_epoch_freq: 10
  model_save_path: "/mnt/data2/users/hilight/yiwei/train/models/"
  save_best_only: False

  fix_backbone: False

val:
  <<: *general
  isTrain: False

test:
  <<: *general
  isTrain: False
  model_path: "./"
  result_save_path: "./"
  no_resize: True
  no_crop: True
  
train_data:
  <<: *general
  data_label: "train"
  data_source: "folder"
  isTrain: True
  image_height: 256
  image_weight: 256
  augmentation: True
  normalization: True
  batch_size: 256
  shuffle: True
  class_sampler: True
  num_threads: 2
  no_crop: False
  cropSize: 224
  no_flip: False
  no_resize: False

  rz_interp: "bilinear,bicubic"
  blur_prob: 0.5
  blur_sig: 0.0,3.0
  jpg_prob: 0.5
  jpg_method: "cv2,pil"
  jpg_qual: "30,100"

val_data:
  <<: *general
  data_label: "val"
  data_source: "folder"
  isTrain: False
  image_height: 256
  image_weight: 256
  augmentation: False
  normalization: True
  batch_size: 256
  shuffle: False
  class_sampler: True
  num_threads: 2
  no_crop: False
  cropSize: 224
  no_flip: True
  no_resize: True

test_data:
  <<: *general
  isTrain: False
  image_height: 256
  image_weight: 256
  augmentation: False
  normalization: True
  batch_size: 1
  shuffle: False
  class_sampler: False
  num_threads: 1
  no_crop: False
  cropSize: 224
  no_flip: True
  no_resize: True

  
  